export const FormKeys = {
  date: "date",
  landlordName: "landlordName",
  landlordAddress: "landlordAddress",
  tenantName: "tenantName",
  tenantAddress: "tenantAddress",
  landlordAddress: "landlordAddress",
  rent: "rent",
};
export const LoanKeys = {
  date: "date",
  lenderName: "lenderName",
  lenderAddress: "lenderAddress",
  borrowerName: "borrowerName",
  borrowerAddress: "borrowerAddress",
  loanAmount: "loanAmount",
  interestRate: "interestRate",
  startDate: "startDate",
  endDate: "endDate",
  installmentAmount: "installmentAmount",
  firstInstallmentDate: "firstInstallmentDate",
  tenantName: "tenantName",
  tenantAddress: "tenantAddress",
  landlordAddress: "landlordAddress",
  rent: "rent",
};
export const BusinessKeys = {
  date: "date",
  partyA: "partyA",
  businessType: "businessType",
  addressPartyA: "addressPartyA",
  partyB: "partyB",
  addressPartyB: "addressPartyB",
  businessDesc: "businessDesc",
  payment: "payment",
  endingDate: "endingDate",
  dueDate: "dueDate",
  landlordAddress: "landlordAddress",
  rent: "rent",
};
export const EmpKeys = {
  date: "date",
  employerName: "employerName",
  employerAddress: "employerAddress",
  employeeName: "employeeName",
  employeeAddress: "employeeAddress",
  startDate: "startDate",
  endDate: "endDate",
  paymentFreq: "paymentFreq",
  empBenefits: "empBenefits",
  jobTitle: "jobTitle",
};
